Repository codesquad-member-2020/dust-1, pull requests merged in 2020-03, with the labels that each got.

#15 [#5] Chore: 개발환경 세팅
  .gitignore
  FE/.babelrc
  FE/package-lock.json
  FE/package.json
  FE/src/index.html
  FE/src/js/main.js
  FE/src/scss/base/_reset.scss
  FE/src/scss/base/_typography.scss
  FE/src/scss/components/_graph.scss
  FE/src/scss/components/_progress-bar.scss
  FE/src/scss/layout/_grid.scss
  FE/src/scss/layout/_tab.scss
  FE/src/scss/main.scss
  FE/src/scss/pages/_dust.scss
  FE/src/scss/pages/_forecast.scss
  FE/src/scss/utils/_variables.scss
  FE/webpack.config.js
Labels: Feature

#17 [#3] README.md 작성
  README.md
Labels: Team, documentation

#18 [#3] 사용자 깃헙 프로파일로 연결되는 링크 오류 수정
  README.md
Labels: bug

#19 [#3] README.md 수정
  FE/.gitignore
  README.md
Labels: documentation

#27 [#6] Feat: HTML 구조 작성
  FE/src/index.html
Labels: Feature

#35 [#7] Feat: CSS 작성
  FE/package.json
  FE/src/index.html
  FE/src/scss/base/_reset.scss
  FE/src/scss/base/_typography.scss
  FE/src/scss/components/_progress-bar.scss
  FE/src/scss/layout/_grid.scss
  FE/src/scss/layout/_tab.scss
  FE/src/scss/pages/_dust.scss
  FE/src/scss/pages/_forecast.scss
  FE/src/scss/utils/_variables.scss
  FE/webpack.config.js
Labels: Feature

#37 [#33] Feat: GET station-dust-status Mock API 구현
  BE/README.md
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
  BE/src/main/java/com/codesquad/team1/dust/domain/DustStatus.java
Labels: Feature

#38 [#34] Feat: GET station-위도-경도 Mock API 구현
  BE/README.md
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
Labels: Feature

#44 [#43] Feat: GET forecast Mock API 구현
  BE/README.md
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
  BE/src/main/java/com/codesquad/team1/dust/domain/Forecast.java
  BE/src/main/java/com/codesquad/team1/dust/domain/Image.java
Labels: Feature

#45 [#42] Feat: GET daily-dust-status Mock API 구현
  BE/README.md
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
  BE/src/main/java/com/codesquad/team1/dust/domain/DustStatus.java
Labels: Feature, enhancement

#50 [#41] Test: Application Context와 Logger가 잘 불러와지는지 테스트하는 코드 작성
  BE/src/test/java/com/codesquad/team1/dust/DustApplicationTests.java
Labels: Test

#52 [#51] gradle wrapper를 사용하기 위해 필요한 파일 추가
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
Labels: bug

#54 [#49] Feat: API Docs Swagger 설정
  BE/README.md
  BE/build.gradle
  BE/src/main/java/com/codesquad/team1/dust/config/SpringFoxConfig.java
Labels: Feature, documentation

#57 [#56] Fix: Cors 에러를 해결하는 설정 추가
  BE/src/main/java/com/codesquad/team1/dust/config/WebConfig.java
Labels: bug
