Repository codesquad-member-2020/dust-1, pull requests merged in 2020-04, with the labels that each got.

#64 [#15] 미세먼지 그래프 기능 구현
  FE/src/index.html
  FE/src/js/components/fetch.js
  FE/src/js/components/graph.js
  FE/src/js/components/tab.js
  FE/src/js/main.js
  FE/src/js/utils/constants.js
  FE/src/js/utils/mockData.js
  FE/src/js/utils/utils.js
  FE/src/scss/base/_typography.scss
  FE/src/scss/components/_graph.scss
  FE/src/scss/components/_progress-bar.scss
  FE/src/scss/layout/_grid.scss
  FE/src/scss/layout/_tab.scss
  FE/src/scss/pages/_dust.scss
  FE/src/scss/pages/_forecast.scss
  FE/src/scss/utils/_variables.scss
Labels: Feature

#66 [#65] Fix: Forecast API 반환 타입 수정
  BE/README.md
  BE/src/main/java/com/codesquad/team1/dust/domain/Forecast.java
Labels: Team, bug, documentation

#68 [#61] 아파치 서버에 빌드된 파일 띄우기
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
  BE/src/main/java/com/codesquad/team1/dust/constants/CommonConstants.java
  BE/src/main/java/com/codesquad/team1/dust/domain/Forecast.java
  FE/src/index.html
  FE/src/js/components/fetch.js
  FE/src/js/components/graph.js
  FE/src/js/components/tab.js
  FE/src/js/main.js
  FE/src/js/utils/constants.js
  FE/src/js/utils/mockData.js
  FE/src/js/utils/utils.js
  FE/src/scss/base/_typography.scss
  FE/src/scss/components/_graph.scss
  FE/src/scss/components/_progress-bar.scss
  FE/src/scss/layout/_grid.scss
  FE/src/scss/layout/_tab.scss
  FE/src/scss/pages/_dust.scss
  FE/src/scss/pages/_forecast.scss
  FE/src/scss/utils/_variables.scss
Labels: Feature

#69 [#10] Feat: 미세먼지 상태 변경 기능 구현
  FE/src/index.html
  FE/src/js/components/dustStatus.js
  FE/src/js/components/fetch.js
  FE/src/js/components/graph.js
  FE/src/js/components/tab.js
  FE/src/js/main.js
  FE/src/js/utils/constants.js
  FE/src/js/utils/utils.js
  FE/src/scss/base/_reset.scss
  FE/src/scss/components/_graph.scss
  FE/src/scss/components/_progress-bar.scss
  FE/src/scss/layout/_grid.scss
  FE/src/scss/pages/_dust.scss
  FE/src/scss/pages/_forecast.scss
  FE/src/scss/utils/_variables.scss
Labels: Feature

#84 [#81] Feat: h2 DB 세팅
  BE/build.gradle
  BE/src/main/resources/application-develop.properties
  BE/src/main/resources/application-local.properties
  BE/src/main/resources/application.properties
Labels: Feature

#85 [#83] Refactor: org.json to jackson library migration
  BE/build.gradle
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
  BE/src/main/java/com/codesquad/team1/dust/domain/DustStatus.java
  BE/src/main/java/com/codesquad/team1/dust/domain/Forecast.java
  BE/src/main/java/com/codesquad/team1/dust/domain/StationLocation.java
  BE/src/main/java/com/codesquad/team1/dust/util/KakaoAPIUtils.java
  BE/src/main/java/com/codesquad/team1/dust/util/PublicAPIUtils.java
Labels: enhancement

#88 [#87] Feat: Mock API를 다시 제공합니다.
  BE/src/main/java/com/codesquad/team1/dust/api/MockFineDustApiController.java
  BE/src/main/java/com/codesquad/team1/dust/domain/DustStatus.java
  BE/src/main/java/com/codesquad/team1/dust/domain/Forecast.java
Labels: Feature

#90 [#13] 예보 탭 진행 바 기능
  FE/src/index.html
  FE/src/js/components/dustStatus.js
  FE/src/js/components/fetch.js
  FE/src/js/components/forecast.js
  FE/src/js/components/gps.js
  FE/src/js/components/graph.js
  FE/src/js/components/progressBar.js
  FE/src/js/components/tab.js
  FE/src/js/main.js
  FE/src/js/utils/constants.js
  FE/src/js/utils/utils.js
  FE/src/scss/components/_progress-bar.scss
  FE/src/scss/layout/_tab.scss
  FE/src/scss/pages/_dust.scss
  FE/src/scss/pages/_forecast.scss
  FE/src/scss/utils/_variables.scss
Labels: Feature

#94 [#91] 이미지 변경 기능 구현
  FE/src/index.html
  FE/src/js/components/fetch.js
  FE/src/js/components/forecast.js
  FE/src/js/components/imageChanger.js
  FE/src/js/components/progressBar.js
  FE/src/js/components/tab.js
  FE/src/scss/components/_progress-bar.scss
  FE/src/scss/pages/_forecast.scss
  FE/src/scss/utils/_variables.scss
Labels: Feature

#96 [#95] Refactor: 위경도 전송하면 가장 가까운 관측소의 24시간 관측값 리스트 반환
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
Labels: enhancement

#97 [#78] Feat: Batch Job 작성
  BE/README.md
  BE/src/main/java/com/codesquad/team1/dust/DustApplication.java
  BE/src/main/java/com/codesquad/team1/dust/aggregate/DailyDustStatusJson.java
  BE/src/main/java/com/codesquad/team1/dust/aggregate/DailyDustStatusJsonRepository.java
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
  BE/src/main/java/com/codesquad/team1/dust/batch/ScheduledTasks.java
  BE/src/main/java/com/codesquad/team1/dust/util/PublicAPIUtils.java
  BE/src/main/resources/schema.sql
Labels: Feature

#100 [BE] Feat: 로그 파일 쌓기
  BE/src/main/resources/application-develop.properties
  BE/src/main/resources/application-local.properties
  BE/src/main/resources/application-master.properties
Labels: Feature

#101 Dust Project Production Version 1.2.0
  BE/README.md
  BE/src/main/java/com/codesquad/team1/dust/DustApplication.java
  BE/src/main/java/com/codesquad/team1/dust/aggregate/DailyDustStatusJson.java
  BE/src/main/java/com/codesquad/team1/dust/aggregate/DailyDustStatusJsonRepository.java
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
  BE/src/main/java/com/codesquad/team1/dust/batch/ScheduledTasks.java
  BE/src/main/java/com/codesquad/team1/dust/util/PublicAPIUtils.java
  BE/src/main/resources/application-develop.properties
  BE/src/main/resources/application-local.properties
  BE/src/main/resources/application-master.properties
  BE/src/main/resources/schema.sql
  FE/src/js/components/fetch.js
  FE/src/js/components/forecast.js
  FE/src/js/components/imageChanger.js
  FE/src/js/components/progressBar.js
  FE/src/js/components/tab.js
  FE/src/scss/components/_progress-bar.scss
  FE/src/scss/pages/_forecast.scss
  FE/src/scss/utils/_variables.scss
Labels: deploy

#102 [#80] 로딩 페이지, 미세먼지 표 제작
  FE/src/index.html
  FE/src/js/components/fetch.js
  FE/src/js/components/forecast.js
  FE/src/js/components/loadingPage.js
  FE/src/js/main.js
  FE/src/js/utils/constants.js
  FE/src/scss/components/_loadingPage.scss
  FE/src/scss/layout/_tab.scss
  FE/src/scss/main.scss
  FE/src/scss/pages/_forecast.scss
  FE/src/scss/utils/_variables.scss
Labels: Feature

#103 Revert "[#78] Feat: Batch Job 작성"
  BE/README.md
  BE/src/main/java/com/codesquad/team1/dust/DustApplication.java
  BE/src/main/java/com/codesquad/team1/dust/aggregate/DailyDustStatusJson.java
  BE/src/main/java/com/codesquad/team1/dust/aggregate/DailyDustStatusJsonRepository.java
  BE/src/main/java/com/codesquad/team1/dust/api/FineDustApiController.java
  BE/src/main/java/com/codesquad/team1/dust/batch/ScheduledTasks.java
  BE/src/main/java/com/codesquad/team1/dust/util/PublicAPIUtils.java
  BE/src/main/resources/schema.sql
Labels: bug
